# Generated by Django 4.2.4 on 2023-08-05 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabdeal_B2B', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('rate', models.IntegerField(default=0)),
                ('free', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
