# Generated by Django 4.2.4 on 2023-08-05 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tabdeal_B2B', '0002_book_delete_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=10)),
                ('price', models.IntegerField(choices=[('b', 'black'), ('w', 'white')])),
            ],
        ),
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.AddField(
            model_name='car',
            name='factory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabdeal_B2B.factory'),
        ),
    ]
