# Generated by Django 4.2.4 on 2023-08-10 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tabdeal_B2B', '0004_seller_transaction_delete_car_delete_factory'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='history_of_transactions',
            field=models.ManyToManyField(related_name='sellers_transactions', to='tabdeal_B2B.transaction'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='credits',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='tabdeal_B2B.seller'),
        ),
        migrations.CreateModel(
            name='IncreaseCredits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='increase_credits', to='tabdeal_B2B.seller')),
            ],
        ),
        migrations.AddField(
            model_name='seller',
            name='history_of_increase_credits',
            field=models.ManyToManyField(related_name='sellers_increase_credits', to='tabdeal_B2B.increasecredits'),
        ),
    ]
