# Generated by Django 4.2.4 on 2023-08-10 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabdeal_B2B', '0005_seller_history_of_transactions_alter_seller_credits_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='history_of_increase_credits',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='history_of_transactions',
        ),
    ]
