# Generated by Django 4.2.4 on 2023-08-10 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabdeal_B2B', '0006_remove_seller_history_of_increase_credits_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IncreaseCredits',
            new_name='IncreaseCredit',
        ),
    ]
